// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD12iOefhSbZxzfyQ6kwl7WvbN-dkUKBVE',
    appId: '1:702871097154:web:dc5ba43b221c0945e042db',
    messagingSenderId: '702871097154',
    projectId: 'chatapp-aa15d',
    authDomain: 'chatapp-aa15d.firebaseapp.com',
    storageBucket: 'chatapp-aa15d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5euW_liAOI3tjZ1VxBkpToXvneNDeT4g',
    appId: '1:702871097154:android:13eaddb696deb9cee042db',
    messagingSenderId: '702871097154',
    projectId: 'chatapp-aa15d',
    storageBucket: 'chatapp-aa15d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzPFrqlXLMOuLxs8bedWQs9AY4Q9Pu8dw',
    appId: '1:702871097154:ios:3ce0348a7802348de042db',
    messagingSenderId: '702871097154',
    projectId: 'chatapp-aa15d',
    storageBucket: 'chatapp-aa15d.appspot.com',
    iosBundleId: 'com.example.chatAppFirebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzPFrqlXLMOuLxs8bedWQs9AY4Q9Pu8dw',
    appId: '1:702871097154:ios:ad47f7b2aaf22622e042db',
    messagingSenderId: '702871097154',
    projectId: 'chatapp-aa15d',
    storageBucket: 'chatapp-aa15d.appspot.com',
    iosBundleId: 'com.example.chatAppFirebaseFlutter.RunnerTests',
  );
}
